# Generated by Django 6.0.6 on 2026-06-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_completemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteModel',
        ),
    ]
