# Generated by Django 6.0.6 on 2026-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_taskmodel_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
