# Generated by Django 6.0.6 on 2026-06-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0007_alter_taskmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='user',
        ),
    ]
