# Generated by Django 6.0.6 on 2026-06-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0009_taskmodel_host_taskmodel_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='host',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_delete',
        ),
    ]
