# Generated by Django 6.0.6 on 2026-06-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0011_taskmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
